name: Run benchmarks
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and benchmark
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig build bench -Doptimize=Debug --summary all
      - run: zig build bench -Doptimize=ReleaseSafe --summary all
