name: Run benchmarks
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and benchmark
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: echo "Benchmark for current changes"
      - run: zig build bench -Doptimize=Debug --summary all
      - run: zig build bench -Doptimize=ReleaseSafe --summary all
      - run: echo "Benchmark for previous commit"
      - run: git reset --hard HEAD~1
      - run: zig build bench -Doptimize=Debug --summary all
      - run: zig build bench -Doptimize=ReleaseSafe --summary all
