name: Run benchmarks
on: 
  # push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and benchmark
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.3239+d7b93c787
      - run: echo "Benchmark for current changes" && rm -rf /home/runner/.cache/zig
      - run: zig build bench -Doptimize=Debug --summary all
      - run: zig build bench -Doptimize=ReleaseSafe --summary all
      - run: echo "Benchmark for previous commit" && git reset --hard HEAD~1 && zig build clean-all && rm -rf /home/runner/.cache/zig
      - run: zig build bench -Doptimize=Debug --summary all
      - run: zig build bench -Doptimize=ReleaseSafe --summary all
