name: Run tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0-dev.3012+3348478fc
      - run: zig build test --summary all
